# Generated by Django 2.0.5 on 2018-05-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_comprehensible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='is_correct_info',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='is_email',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='is_spam',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
