# Generated by Django 2.0.5 on 2018-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0003_auto_20180601_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='assignmentId',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
